### ISSUE TITLE
Testing Boost example data

### ISSUE THREAD

**Issue by veenits123** [veenits123/GSoC-pgRouting#5]
## Drawing:

![test_boostExample](https://user-images.githubusercontent.com/39950919/113249865-199bca00-92dd-11eb-81ab-641d9aa71f5b.jpeg)

## Setup:

DROP TABLE IF EXISTS boost_example;

CREATE TABLE boost_example (
          id BIGSERIAL,
          source BIGINT,
          target BIGINT,
          cost FLOAT,
          reverse_cost FLOAT
);
```
CREATE TABLE
```

INSERT INTO boost_example (source, target,
           cost, reverse_cost) VALUES 
(1, 4, 1, 1),
(1, 6, 1, 1),
(2, 3, 1, 1),
(2, 5, 1, 1),
(2, 7, 1, 1),
(2, 10, 1, 1),
(3, 4, 1, 1),
(3, 5, 1, 1),
(4, 6, 1, 1),
(4, 9, 1, 1),
(5, 7, 1, 1),
(6, 7, 1, 1),
(6, 8, 1, 1),
(7, 8, 1, 1);
```
INSERT 0 14
```
## Result:

SELECT * FROM pgr_dijkstra('SELECT * FROM boost_example', 1, 10, directed => false);
```
 seq | path_seq | node | edge | cost | agg_cost 
-----+----------+------+------+------+----------
   1 |        1 |    1 |    2 |    1 |        0
   2 |        2 |    6 |   12 |    1 |        1
   3 |        3 |    7 |    5 |    1 |        2
   4 |        4 |    2 |    6 |    1 |        3
   5 |        5 |   10 |   -1 |    0 |        4
(5 rows)
```
![final_test_boostExample](https://user-images.githubusercontent.com/39950919/113251368-c9723700-92df-11eb-914b-0ab3cafc4376.jpeg)

![Screenshot from 2021-03-31 20-36-53](https://user-images.githubusercontent.com/39950919/113167245-28dd3200-9261-11eb-9ff0-810d0c3eaa40.png)

**Comment by Veenits123** [comment]
![Screenshot from 2021-03-29 00-39-51](https://user-images.githubusercontent.com/39950919/112764671-59d22280-9027-11eb-95a4-4c53e95a4cd2.png)
