### ISSUE TITLE
pgtap's types_check.sql

### ISSUE THREAD

**Issue by cvvergara** [veenits123/GSoC-pgRouting#6]
Non of your test will pass,
you used camel case and postgres converts everything to lower case:
This fails
```
RETURN QUERY
SELECT has_function('pgr_edgeColoring');
```
this pass:
```
RETURN QUERY
SELECT has_function('pgr_edgecoloring');
```

**Comment by veenits123** [comment]
We have to convert this also to lower case: https://github.com/veenits123/GSoC-pgRouting/blob/64eac52789b124d9c42478d52228b44720519284/pgtap/coloring/edgeColoring/types_check.sql#L24
and this: https://github.com/veenits123/GSoC-pgRouting/blob/64eac52789b124d9c42478d52228b44720519284/pgtap/coloring/edgeColoring/types_check.sql#L28
???
